### ISSUE TITLE
Module 4

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-rommelcarneiro#10]
👋 Hi @rommelcarneiro you are missing the Module 4.1 Assignment. Please post it here in this thread.

**Comment by rommelcarneiro** [comment]
@arelia and @ericdrosado, I thought it's just needed to post message to the community. My post made on May/2020 follows.

rommelcarneiro
Rommel Vieira Carneiro
May '20
1. Describe the existing technical student communities on your campus. Who is served? Where are there gaps?
We have a community of about 3K students in information technology / computer science courses. They are distributed in five courses: Computer Science, Computer Engineering, Digital Games, Information Systems, Software Engineering. We are very focused in provide tools and educational methodology to interdisciplinary work to allow students to learn by doing collaboratively. At this moment, students are choosing frameworks by their own and we would like to standardize some practices as it could help them to evolve better.

2. Choose one GitHub Education program. How could it support your on-campus student communities?
GitHub Student Developer Pack could help us to provide a complete framework to all courses as the starter kit to our students. We already have some partnership and this program could complement our framework.

3. What would you need to do in order to support the growth of student tech communities on campus?
Bring some teachers to understand the structure of programs like GitHub Campus Advisor and to participate of them to be prepared in order to assist our students with all these tools in the classroom. At this moment, we are creating a faculty community focused in GitHub to participate on Campus Advisor training course and start to implement GitHub classroom in our interdisciplinary disciplines.
![github_advisor](https://user-images.githubusercontent.com/15574170/145931405-944a0619-d5c1-469d-97f3-4c5d509a3e78.png)
